module = "icon"

[glyphs]
clipboard = "fontawesome-docs"
clock = "fontawesome-clock"
collapse = "fontawesome-collapse-left"
expand = "fontawesome-expand-right"
download = "fontawesome-download"
heart = "entypo-heart"
trash = "fontawesome-trash"
user = "iconic-user"
arrow_up = "entypo-up-open"
arrow_down = "entypo-down-open"
arrow_right = "entypo-right-open"
refresh = "typicons-arrows-cw"
globe = "linecons-globe"
link = "fontawesome-link-ext"
