name: Dockerize
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/dockerize.yml'
      - 'docker/rocm.Dockerfile'
permissions:
  packages: write
jobs:
  push_to_registry:
    name: rocm
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Free Disk Space (Ubuntu)
        uses: ggml-org/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Build and push server Docker image (tagged + versioned)
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/llama.cpp:server-rocm
          file: docker/rocm.Dockerfile
          target: server
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
