name: Lint
on: [push, pull_request]
jobs:
  all:
    runs-on: macOS-latest
    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        components: clippy
    - uses: actions/checkout@master
    - name: Check lints
      run: cargo lint
